application: dawgtunes
version: 1
runtime: pythond27
api_version: 1
threadsafe: true

handlers:
-url: /
static_dir: assets

-url: /create
#....

-url: /requests

- url: .*
  script: dawgtunes_code.application

Libraries:
- name: webapp2 
  version: latest
- name: jinja2
  version: latest 